### ISSUE TITLE
Resource package file

### ISSUE THREAD

**Issue by InfGithub** [ZLT9/create-modular-tools-fabric#3]
create_modular_tools-0.1.1+1.20.1
[Create Modular Tools zh_cn.zip](https://github.com/user-attachments/files/17147044/Create.Modular.Tools.zh_cn.zip)

本身为资源包。解压后可查看翻译文件。也许它并不恰当，如有想法请联系。
It is a resource plan. After unzipping it, you can view the translated file. Maybe it's not appropriate, if you have any ideas, please get in.

Email:Yao_icft@outlook.com

**Comment by InfGithub** [comment]
![image](https://github.com/user-attachments/assets/723fd7a5-65fa-4d6a-b80f-8e7e45e0c5be)

Sheep is cute   q(≧▽≦q)

我提出一些建议。让沙盘在方块状态下仍能与一些方块进行工作。
同时，希望能够制作拥有工具部件凹槽的沙盘，以便自动化制作更加强大的工具。
我还想让每个工具部件进行附魔，以便让工具变得更加强大。
这些想法可能实现过程稍微会困难，但是可以慢慢来，努力让模组变得更好。

I have some suggestions. Make the sandbox work with some blocks while in a block state.
At the same time, it is desirable to be able to make a sand table with grooves in the tool parts, so that the automation can make more powerful tools.
I also want to enchant each tool part to make it more powerful.
These ideas may be a little more difficult to implement, but you can take your time and try to make the mod better.

![image](https://github.com/user-attachments/assets/edb22326-681f-451a-8676-e1d6f2fb9058)
![image](https://github.com/user-attachments/assets/f20a6b78-32de-4fd8-9c0a-b410bde6404a)
![image](https://github.com/user-attachments/assets/40fa3784-60bd-4f99-be56-ea2349f93c1d)
![image](https://github.com/user-attachments/assets/7d262374-3802-472f-a62a-20c75b4f7e6b)

**Comment by ZLT9** [comment]
Hi again!

Thank you so much for your feedback and for taking the time to create a Chinese translation resource pack for my mod. I really appreciate your contribution to making it more accessible! Since the mod is still in alpha and I'm actively updating it with new features (which could add, remove, or modify entries in the language files), I feel it's a bit early to include additional languages directly in the mod. However, I fully support your efforts and encourage you to publish your resource pack on Modrinth or other platforms if you'd like! I'd be happy to point users toward it in the future.

As for the idea of enchanting tool modules individually, it's something I had envisioned from the start but was unsure about how well it would fit the mod. Seeing that you also thought it would be a great addition gave me the confidence to move forward with it, and I'm excited to let you know that it's now implemented in the new Alpha 0.2.0 release. I hope you enjoy this new feature, and I'd love to hear your thoughts on it!

Thank you again for your support and for being part of the journey to improve Create: Modular Tools.

**Comment by InfGithub** [comment]
Great, I'm going to try these new features!
